### ISSUE TITLE
Source files don't get submitted

### ISSUE THREAD

**Issue by ronalchn** [Faylixe/googlecodejam-cli#5] opened 2016-04-09 09:12 UTC
My submissions using this tool don't submit the source file:

```
java -jar googlecodejam-cli.jar --submit --problem B --inputtype large --output B-large-0.out --sourcefile B.cpp
Submission correct !
```

But B.cpp isn't submitted

**Comment by Faylixe** [comment] 2016-04-09 10:13
Which OS, Java version and could you run the same command using the --verbose option ?

**Comment by ronalchn** [comment] 2016-04-09 10:31
I can't submit anymore. I got 100 already.

I am on Windows, with MinGW, win-bash environment.

**Comment by Faylixe** [comment] 2016-04-09 19:02
I got the same issues here, have to dig this, i will try to fix it for the Round 1A.

**Comment by Faylixe** [comment] 2016-04-14 10:54
Unfortunately i cannot test it before next round. It seems that file are correctly uploaded but the built archive on code jam platform with your source code is corrupted because the file entry in the zip does not have a file name. Although the archive does contains the uploaded the source file (check crc32 on your archive to be sure). It does not seems to have an impact on submission though (did it for one small input and was not rejected, I think the file is analysed during the upload process so it does not matter. Hope I will get this fixed quick though.

**Comment by veltzerdoron** [comment] 2016-04-29 04:54
Any news on this issue?

**Comment by Faylixe** [comment] 2016-04-29 05:35
Not really, I asked for a test server but I didn't get any news :(. File
are uploaded though the archive is just corrupted.

Le vendredi 29 avril 2016, vetlzerdoron notifications@github.com a écrit :

> Any news on this issue?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/Faylixe/googlecodejam-cli/issues/5#issuecomment-215626777

## 

---

_Félix Voituret_
_Research and development engineer_
_iSmart, SmartLab, Kware_
_www.ismart.fr http://www.ismart.fr_
Phone : +33 6 48 95 75 46, Fax : +33 4 42 24 45 78

**Comment by Faylixe** [comment] 2017-04-11 12:13
#8

**Comment by alayouni** [comment] 2017-04-15 05:21
My findings after debugging:

- HttpRequestExecutor#buildFilePart() is calling Files.probeContentType(file.toPath()) to fetch file mime type, the call always returns null (at least in my Mac), it seems to be a known unfixed jdk bug (see [here](http://stackoverflow.com/questions/12407479/why-does-files-probecontenttype-return-null)). I used new Tika().detect(file) from org.apache.tika-tika-core to workaround it, it fetched the type properly but the main bug (corrupted zip file) remained. 

- Debugging mime types further with chrome console from the website, I noticed chrome uses 'application/octet' for both output and source (java source in my case), which is not same as what Tika returns ('text/plain', and 'text/x-java-source'). I hard coded 'application/octet' and tested, the bug persisted.

- My last finding is what I believe is key: CodeJamSession#createContent() is missing an important header i.e. "source-file-name0" with the path of the source file in content. I unfortunately only noticed this after the contest ended  so I could not test a fix, but I think this should be it. The server presumably needs the file name to create the downloadable zip and when it doesn't find it, it's probably generating the zip with an empty file name, which would for sure cause the zip corruption.

Here's a preview of a request submitted by chrome through the website during the contest, it shows  all request headers:
https://justpaste.it/15jgg

I'll gladly submit a pull request with a fix if you grant me permission.

Let me know if any questions

**Comment by alayouni** [comment] 2017-04-15 05:35
In case you noticed the 'C:\fakepath\A-small-0.java' in the chrome request preview I shared, Chrome actually does it for security, the server should not have access to clients file system details.

By the way let me know if you expect me to submit a pull request, or if you'd rather apply the fixes yourself... shouldn't take more than a couple minutes.

**Comment by alayouni** [comment] 2017-04-15 13:20
By the way I'll be happy to submit a pull request with a fix if you grant me permission.

**Comment by Faylixe** [comment] 2017-04-15 13:47
Sure, sorry i do not have that much time, but please submit the pull request, and i will check it ASAP !

**Comment by alayouni** [comment] 2017-04-15 15:42
I cannot submit a pull request without write permission to the git repo, here's what I get when I try to push my changes:
remote: Permission to Faylixe/googlecodejam-client.git denied to alayouni

I'll be able to write to the repo if you add me as a collaborator. You can add me as a collaborator from Settings -> Collaborators [here](https://github.com/Faylixe/googlecodejam-client)

**Comment by Faylixe** [comment] 2017-04-15 16:02
You have to fork the repository, then push change into your fork and then submit a pull request from github web UI 

Envoyé de mon iPhone

**Comment by alayouni** [comment] 2017-04-15 16:04
That's what I did, did you add me as a collaborator?

**Comment by alayouni** [comment] 2017-04-15 16:06
ah sorry I get what you mean, wouldn't it be easier if you just add me as a collab though? :)

**Comment by alayouni** [comment] 2017-04-15 16:35
Just submitted the pull request.

Sorry again, I'm used to pull requests from same repo/different branch but not the fork way, this is my first pull request through fork :)

**Comment by Faylixe** [comment] 2017-04-21 09:52
Thanks to @alayouni, the problem is supposed to be now fixed. The last release v1.4.1 should perform source file submission and don't generate any issues on code jam servers.

**Closed as completed by Faylixe** 2017-04-21 09:52 UTC
Labels: bug, enhancement, help wanted

**Comment by alayouni** [comment] 2017-04-21 14:13
I've been having a second look to avoid surprises during the contest tomorrow by comparing what google's python tool does vs yours.

**The python tool** decides whether to zip the files on the client side depending on user configuration (true by default). If configured to zip, the source files get zipped on the client side before submitting the request, and 'Content-Encoding' is set to 'gzip' on the request header. If configured not to zip, the source files are submitted in plain format and 'Content-Encoding' is set to 'text/plain'.

**'Our' tool** seems to be not zipping the files on the client side (I set a watch break point on com.google.api.client.http.GZipEncoding.encode but it never got hit, would be great if you could confirm?), and it is not setting the 'Content-Encoding' header on the request which looks fine since it is what chrome does, but I'm not sure if chrome actually compresses files automatically (for performance maybe) or not before posting the request, which if true would be different from what our client does and could cause the bug to persist. I couldn't find a way to figure out whether chrome automatically compresses files.

If you can confirm for sure whether the source files get zipped or not by the tool before submission, then setting the 'Content-Encoding' header accordingly would prevent surprises.

Maybe I'm worrying too much here, I'm just trying to prevent surprises.

Sorry I haven't noticed this earlier :)

**Comment by Faylixe** [comment] 2017-04-22 15:09
Well, i think ZIP is used when multiple source files are submitted, but since in support both, there is no reason to have issue with it. As i said, i used it during last year qualification round, didn't had any trouble even with the corrupted zip archive issues :)

**Comment by alayouni** [comment] 2017-04-22 18:42
Makes sense, were you able to use the tool in the round though? I couldn't even initialize the contest  :'|

**Comment by Faylixe** [comment] 2017-04-22 18:52
Didn't used it no. I will check that monday, but before to publish the new version I tried on my desktop computer (ubuntu) and initialization worked. Which platform did you used ?

**Comment by alayouni** [comment] 2017-04-22 18:59
Mac os, trying to figure out what's wrong before I submit a new issue

**Comment by alayouni** [comment] 2017-04-30 11:35
Confirmed the bug is fixed :)
